SELECT
PAT.TASK_SEQUENCE AS Sr_No
,papf.person_number
,PersonName.DISPLAY_NAME Person_Name
,PAT.TASK_COMMENTS AS Comments
,PerformerName.DISPLAY_NAME AS USER_NAMES
,PAC.ALLOCATED_CHECKLIST_ID AS ALLOCATED_CHECKLIST_ID
,PAT.allocated_task_id
,papf.person_id
,(SELECT DISTINCT D.NAME FROM PER_DEPARTMENTS D WHERE D.ORGANIZATION_ID = A.ORGANIZATION_ID AND D.EFFECTIVE_START_DATE BETWEEN D.EFFECTIVE_START_DATE AND D.EFFECTIVE_END_DATE) AS DEPARTMENT
,PAC.ALLOCATION_DETAILS AS Assigned_Journey_Comments
--,PAT.STATUS AS ACTION_STATUS
,DECODE(PAT.STATUS, 'INI', 'Pending', 'INP', 'Pending', 'COM', 'Acknowledged', PAT.STATUS) AS ACTION_STATUS
FROM 
PER_PERSONS Person,
PER_PERSON_NAMES_F PersonName,
PER_PERSON_NAMES_F PerformerName,
PER_ALLOCATED_CHECKLISTS PAC,
per_all_people_f papf,
PER_ALLOCATED_TASKS_VL PAT,
PER_ALL_ASSIGNMENTS_M A

WHERE 
PAC.ALLOCATED_CHECKLIST_ID = TO_NUMBER((SELECT UTL_RAW.CAST_TO_VARCHAR2(
    UTL_ENCODE.BASE64_DECODE(
        UTL_RAW.CAST_TO_RAW(:P_ALLOCATED_CHECKLIST_ID)
    )
)
FROM DUAL))
--PAC.ALLOCATED_CHECKLIST_ID = NVL(:P_ALLOCATED_CHECKLIST_ID,PAC.ALLOCATED_CHECKLIST_ID)
AND A.PERSON_ID = papf.PERSON_ID
AND PAC.PERSON_ID = Person.PERSON_ID
AND PersonName.PERSON_ID = Person.PERSON_ID
AND PersonName.NAME_TYPE = 'GLOBAL'
AND PerformerName.NAME_TYPE = 'GLOBAL'
AND TRUNC(SYSDATE) BETWEEN PersonName.EFFECTIVE_START_DATE AND PersonName.EFFECTIVE_END_DATE
AND TRUNC(SYSDATE) BETWEEN PerformerName.EFFECTIVE_START_DATE AND PerformerName.EFFECTIVE_END_DATE
AND TRUNC(SYSDATE) BETWEEN papf.EFFECTIVE_START_DATE AND papf.EFFECTIVE_END_DATE
AND PAC.ALLOCATED_CHECKLIST_ID=PAT.ALLOCATED_CHECKLIST_ID(+)
AND A.ASSIGNMENT_TYPE IN ('E','C')
AND A.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
AND A.PRIMARY_FLAG = 'Y'
AND A.EFFECTIVE_LATEST_CHANGE = 'Y'
AND TRUNC(SYSDATE) BETWEEN A.EFFECTIVE_START_DATE AND A.EFFECTIVE_END_DATE
--AND PAT.allocated_task_id = PAC.allocated_task_id
AND PAT.PERFORMER_ORIG_SYS_ID = PerformerName.PERSON_ID
--AND PAT.allocated_task_id IN ('300000017240995')
--AND PAT.STATUS IN ('COM', 'REJ', 'DEP', 'EXP', 'FDC', 'INI', 'INP')
AND PAT.STATUS IN ('COM','INP', 'INI')
AND GREATEST(TRUNC(PAC.ACTION_DATE),TRUNC(SYSDATE)) BETWEEN LEAST(TRUNC(SYSDATE),PersonName.EFFECTIVE_START_DATE) AND PersonName.EFFECTIVE_END_DATE
AND PAPF.person_id = Person.PERSON_ID
--AND PAC.ALLOCATION_DETAILS = 'Done'
--and PAT.TASK_SEQUENCE = 1
--OR PAT.TASK_COMMENTS IS NOT NULL
ORDER BY PAT.TASK_SEQUENCE